name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image for CentOS 7
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            getpagespeed/rhel:centos7-lts
            getpagespeed/rhel:el7-lts
            getpagespeed/rhel:latest # Adjust this if you want the latest to point to a specific version
          file: ./Dockerfile.el7

      - name: Build and push Docker image for CentOS 8
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            getpagespeed/rhel:centos8-lts
            getpagespeed/rhel:el8-lts
          file: ./Dockerfile.centos8

      - name: Build and push Docker image for CentOS 9
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            getpagespeed/rhel:centos9-lts
            getpagespeed/rhel:el9-lts
          file: ./Dockerfile.centos9

      - name: Logout from Docker Hub
        run: docker logout
