name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4

      - name: Set matrix data
        id: set-matrix
        run: echo "matrix=$(jq -c . < ./docker-matrix.json)" >> $GITHUB_OUTPUT

  build-amd64:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for amd64
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          tags: getpagespeed/lts:${{ matrix.name }}-amd64
          file: ${{ matrix.file }}

      - name: Logout from Docker Hub
        run: docker logout

  build-arm64:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image for arm64
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          tags: getpagespeed/lts:${{ matrix.name }}-arm64
          file: ${{ matrix.file }}

      - name: Logout from Docker Hub
        run: docker logout

  combine-manifest:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]  # Wait for both architecture builds to complete
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Combine manifests for multi-architecture image and push
        run: |
          docker buildx imagetools create \
            --tag ${{ matrix.tags }} \  # Tag for multi-architecture image
            getpagespeed/lts:${{ matrix.name }}-amd64 \
            getpagespeed/lts:${{ matrix.name }}-arm64

      - name: Logout from Docker Hub
        run: docker logout
