name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4

      - name: Set matrix data
        id: set-matrix
        run: echo "matrix=$(jq -c . < ./matrix.json)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.configure.outputs.matrix).include }}  # Main matrix from JSON
        platform: [linux/amd64, linux/arm64]  # Nested matrix for platforms

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}  # Use the platform from the nested matrix
          push: true
          tags: ${{ matrix.tags }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}  # Generate tag per platform
          file: ${{ matrix.file }}  # Use Dockerfile from matrix.json

      - name: Logout from Docker Hub
        run: docker logout

  combine-manifest:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        include: ${{ fromJson(needs.configure.outputs.matrix).include }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Logout from Docker Hub
        run: docker logout
